backend:
  name: git-gateway
  branch: main # Tem que ser a branch principal do seu repositório no Github

media_folder: "assets/Portfólio"
public_folder: "/assets/Portfólio"

collections:
  - name: "portfolio_data"
    label: "Portfólio (Fotos)"
    files:
      - label: "Lista de Fotos"
        name: "fotos"
        file: "data/portfolio.json"
        fields:
          - label: "Fotos da Galeria"
            name: "items"
            widget: "list"
            fields:
              - {label: "Título (ex: Ação, Foco)", name: "title", widget: "string"}
              - {label: "Imagem", name: "image", widget: "image"}
